### ISSUE TITLE
Unable to find type [uint].

### ISSUE THREAD

**Issue by bkillay** [Shresht7/PowerShell#2]
Write-TypeWriter -Text "Print characters as if they're being typed on a typewriter"
Unable to find type [uint].
At line:11 char:9
+         [uint] $CPM = 350,
+         ~~~~~~
    + CategoryInfo          : InvalidOperation: (uint:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Suggested Code update adding UINT32 instead of UINT 

function Write-TypeWriter {
    [CmdletBinding(DefaultParameterSetName = "Speed")]
    param (
        # The text to write
        [Parameter(ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [string] $Text = " ",

        # Characters per minute
        [Parameter(ParameterSetName = "CPM")]
        [uint32] $CPM = 350,

        # Speed of the typewriter (150ms by default)
        [Parameter(ParameterSetName = "Speed")]
        [uint32] $Speed = 150,

        # The minimum time for a keystroke (default: 10ms)
        [uint32] $MinSpeed = 10,

        # The list of characters to pause at
        [string[]] $PauseAt = @(" ", "`n"),

        # The multiplier to apply when pausing
        [ValidatePattern("[0-9]+")]
        [uint32] $PauseMultiplier = 3
    )

    begin {
        # Instantiate the Random Object
        $Random = New-Object -TypeName System.Random

        # Calculate the speed based on the given CPM (Characters-Per-Minute) if specified
        if ($PSCmdlet.ParameterSetName -eq "CPM") {
            $Speed = (60 * 1000) / $CPM
        }
    }

    process {
        $Text -split '' | ForEach-Object {
            # Determine the duration to pause for
            $PauseFor = $MinSpeed + $Random.Next($Speed)
            # Apply pause multiplier if the character belongs to the $PauseAt set
            if ($PauseAt -contains $_) {
                $PauseFor *= $PauseMultiplier
            }

            # Write the character to the screen
            Write-Host -NoNewline $_

            # Pause for the duration
            Start-Sleep -Milliseconds $PauseFor
        }
        Write-Host ""
    }

    end {
        # Write an empty newline at the end
        Write-Host ""
    }
}

PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
on Windows 11Pro

**Comment by Shresht7** [comment]
Hey, thanks for taking the time and filing the issue.

It seems PowerShell 5.1 does not infer `[uint]` as `[UInt32]` whereas PowerShell 7 does. (Both correctly infer `[int]` as `Int32`)

Still, doesn't hurt to be explicit about types. I'll fix it shortly. Thanks again!
